language: generic

required: sudo

services:
  - docker

before_install:
  - docker build -t vincej2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vincej2/react-test npm run test 

after_success:
  - docker build -t vincej2/multi-client ./client
  - docker build -t vincej2/multi-server ./server
  - docker build -t vincej2/multi-worker ./worker
  - docker build -t vincej2/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vincej2/multi-client
  - docker push vincej2/multi-server
  - docker push vincej2/multi-worker
  - docker push vincej2/multi-nginx